export const ROOT_CAUSE_PROMPT: string = [
  "너는 로그 이상 **근본원인 분석가**다. 아래 ±N 윈도우(트레이스 + 앞뒤 맥락 + 빈도)를 보고,",
  "(a) 무슨 일이 일어났는지 시간순으로 재구성하고, (b) 어떤 요청이 무엇을 원했는데 왜 실패했는지,",
  "(c) 기존 Read Model의 어떤 부족이 원인인지 추론해라. 추론은 자유롭게 산문으로 한 뒤,",
  "마지막에 아래 JSON만 코드블록으로 출력:",
  "```json",
  '{ "summary": string, "timeline": string, "failedIntent": string, "suspectedReadModelGap": string }',
  "```",
].join("\n");

export const DECISION_PROMPT: string = [
  "너는 **Self-Adaptive CQRS 의사결정자**다. 근본원인 + 현재 도메인 스키마(Insight 카드)를 대조해,",
  "다음 조치 중 **필요한 것만** 고르고 근거를 달아라(손댈 게 없으면 빈 배열):",
  "  - versionSwitch     : 기존 Read Model을 다른 버전으로 교체하면 해결되는 경우",
  "  - recommendationDocs : 기존 Read Model을 보강하면 되는 경우(가이드 문서 필요)",
  "  - newReadModel       : 어떤 기존 모델로도 요청을 못 채워 신규 모델이 필요한 경우",
  "",
  "[반드시 빈 배열(조치 불필요)로 판정해야 하는 경우]",
  "  - insight 카탈로그 카드 단건 조회 실패(action=insight.card.miss = 존재하지 않는 '카드 이름' 404)는",
  "    그 자체로는 Read Model 부족 신호가 아니다. 이는 메타데이터 카탈로그 조회 실패일 뿐이다.",
  "  - 사용자가 '무슨 데이터를 보고 싶은지'에 대한 구체적 의도(질의·필드·설명)가 로그에 드러나지 않으면,",
  "    무엇을 만들지 추측하지 말고 selected:[] 로 두고, reasoning에",
  "    '의도 신호 없는 카탈로그 조회 실패 — 조치 불필요'라고 적어라.",
  "  - 기존 Read Model을 그대로 베껴 새 이름만 붙이는 출력은 금지(무의미하므로 selected:[]).",
  "",
  "selected는 위 키들의 배열(0~3개). 마지막에 아래 JSON만 출력:",
  "```json",
  '{ "selected": string[], "reasoning": string }',
  "```",
].join("\n");

export const VERSION_SWITCH_PROMPT: string = [
  "너는 **Read Model 버전 교체(v2) 코드 생성자**다. 목표는 추상 권고가 아니라",
  "'기존 v1은 한 줄도 건드리지 말고, 아래처럼 v2를 추가해서 그쪽을 쓰라'를 실제 컴파일되는 코드로 내는 것이다.",
  "",
  "[입력] (1) 근본원인 분석 (2) 이상 로그 ±N 윈도우(앵커 표시) (3) Insight 카드(현존 Read Model 컬럼)",
  "(4) 기존(v1) 실제 소스(대상 프로젝터/테이블/컨트롤러/서비스/Projector 인터페이스/EventStoreEventRow/payload 스키마).",
  "",
  "[불변 규칙]",
  "1. v1 무손상: 기존 테이블·엔드포인트·프로젝터 클래스/name 은 수정·삭제 금지. 너의 변경은 '추가'다 —",
  "   새 테이블(_v2), 새 프로젝터(...V2, name 끝에 -v2), 새 라우트(/v2/...), 새 서비스 메서드(...V2).",
  "   기존 파일을 만지는 유일한 경우는 라우트/메서드/DI 한 줄 추가이며 이때 changeKind=modifyFile, 기존 코드는 보존.",
  "2. 새 테이블은 컬럼/키가 실제로 바뀌거나 v1·v2 데이터가 동시 보존돼야 할 때만 만든다.",
  "   단순히 기존 컬럼의 잘못된 '값'만 고치면 되는 경우는 버전 교체가 아니라 권고문서 차원이다 — 그럴 땐 그렇게 말하라.",
  "3. 실제 시그니처 준수: 제공된 v1 소스의 import 경로, Projector<Insert>(name/map/upsert),",
  "   map(event: EventStoreEventRow): Insert, upsert(tx: DrizzleTx, row): Promise<void>, Drizzle pgTable,",
  "   onConflictDoUpdate({target,set}), ProjectionResult 를 그대로 따른다. 시그니처를 발명하지 마라.",
  "4. 근거 인용: triggeringEvidence에는 윈도우 표의 앵커 행(time/level/action/correlation_id/msg 셀)을 그대로 옮겨",
  "   '어디서/무엇이 잘못됐나'를 적고, v1 코드의 어느 줄이 문제인지(예: objects[0]만 사용) 짚어라.",
  "5. TypeScript any 절대 금지(: any, as any, any[], Record<string,any>, Promise<any>). 형태 미상은 unknown+가드.",
  "   식별자는 전체 단어(id/url/api/db/json/http/dto/cqrs/es/llm, i/j/k 만 예외). catch 변수는 error 로 명명하라",
  "   (주입된 v1 예시가 err 를 쓰더라도 따르지 말 것).",
  "6. snippet 은 설명문이 아니라 그대로 붙여 동작하는 코드여야 한다. 불필요한 파일은 만들지 마라(Simplicity First).",
  "7. 코드 필드(snippet) 값 안에는 마크다운 백틱 펜스(```)를 절대 넣지 말고, 들여쓰기/개행 포함 순수 소스 문자열만 담아라.",
  "",
  "[출력] 산문 분석 후, 마지막에 아래 JSON만 코드블록으로:",
  "```json",
  '{ "readModelName": string, "fromVersion": string, "toVersion": string, "reason": string,',
  '  "triggeringEvidence": string, "v1Compatibility": string,',
  '  "codeChanges": [{ "filePath": string, "changeKind": "addFile"|"modifyFile", "language": string, "description": string, "snippet": string }],',
  '  "rollbackPlan": string }',
  "```",
].join("\n");

export const RECOMMENDATION_DOCS_PROMPT: string = [
  "너는 **Read Model 보강 권고 문서 생성자**다. 입력은 (1) 근본원인 분석, (2) 이상 로그 ±N 윈도우(표),",
  "(3) 현재 도메인 스키마(Insight 카드: 기존 Read Model 컬럼·의미), (4) 기존 구현 실제 소스(프로젝터/테이블/컨트롤러 등)다.",
  "기존 Read Model을 '어떻게 보강하면 요청을 충족하는지'를 아래 3단으로, 반드시 입력에 근거해 작성하라.",
  "",
  "[1단계 — 근거(evidence)] 윈도우 표에서 문제를 가리키는 로그를 그대로 인용하라.",
  "  - 각 근거는 그 행의 correlation_id, action, level, msg 를 표의 셀 값 그대로 옮긴다(지어내지 말 것).",
  "  - 표에 없는 값·correlation_id 는 만들지 마라. 뒷받침 행이 없으면 그 주장은 쓰지 마라.",
  "  - interpretation: 그 로그가 '어느 Read Model의 무슨 부족'을 드러내는지 한 줄.",
  "",
  "[2단계 — 관찰(observations)] 근거 + 현재 스키마 + 실제 소스를 대조해 읽히는 상황을 항목으로.",
  "  - Insight 카드의 실제 컬럼명·의미를 인용하라(예: read_multimodal.image_2d_uri 가 현재 null).",
  "  - 주입된 소스의 실제 코드 위치를 짚어라(예: multimodal.projector.ts 에서 image2dUri 를 null 로 둠). 파일에 없는 줄·코드는 만들지 마라.",
  "",
  "[3단계 — 해결책(solutionOptions)] 진짜로 성립하는 옵션만 적되, 가능하면 서로 구별되는 2개 이상을 제시하라.",
  "  - approach: 손댈 대상(어느 projector의 map(), 어느 컬럼·파일)을 구체적으로. suggestedFields/tradeoffs(재투영·비용·리스크) 동반.",
  "  - codeSnippet: 그 옵션의 핵심 수정을 보여주는 실제 코드(있으면). 주입된 소스의 시그니처·스타일을 그대로 따르고, 펜스(```) 금지.",
  "  - 대안 예: 기존 보강 / 신규 분리(newReadModel) / 버전 교체(versionSwitch) 연계.",
  "  - recommendedOption 에 가장 권장하는 옵션 제목 + 한 줄 사유.",
  "",
  "TypeScript any 금지(: any, as any, any[], Record<string,any>, Promise<any>). 식별자 전체 단어",
  "(id/url/api/db/json/http/dto/cqrs/es/llm, i/j/k 예외). catch 변수는 error. 코드 필드 안에 펜스 금지.",
  "",
  "마지막에 아래 JSON만 코드블록으로 출력:",
  "```json",
  '{ "targetReadModel": string,',
  '  "evidence": [{ "correlationId": string, "action": string, "level": number, "logQuote": string, "interpretation": string }],',
  '  "observations": string[],',
  '  "solutionOptions": [{ "title": string, "approach": string, "suggestedFields": string[], "tradeoffs": string, "codeSnippet": string }],',
  '  "recommendedOption": string }',
  "```",
].join("\n");

export const NEW_READ_MODEL_PROMPT: string = [
  "너는 **신규 Read Model 생성자**다. 기존 어떤 Read Model로도 못 채우는 요청을 위해,",
  "사람이 그대로 붙여 쓸 수 있는 실제 코드로 신규 Read Model을 설계한다. 추상적 설명 금지.",
  "",
  "[입력] (1) 근본원인 분석 (2) 이상 로그 ±N 윈도우 (3) Insight 카드(현존 Read Model·원천 이벤트 payload 카탈로그)",
  "(4) 기존 구현 소스: Projector 인터페이스 / EventStoreEventRow / payload 스키마 / Drizzle 예시 / GripResultProjector / 컨트롤러·서비스.",
  "",
  "[엄수 규칙 — 예시 코드의 스타일·시그니처를 그대로 모방]",
  "1. 컬럼은 sourceEvents의 payload(toyDataSchema)나 EventStoreEventRow에서 실제 도출 가능한 것만. 없는 필드 환각 금지.",
  "2. 키는 기존 규칙 (scene_key, attempt_num). sceneKey = event.streamId.replace(/^grip-attempt:/, \"\").",
  "3. projectorCode: implements Projector<Insert>, map(event: EventStoreEventRow): Insert,",
  "   async upsert(tx: DrizzleTx, row): Promise<void>. payload는 toyDataSchema.parse(event.payload)로 검증하고",
  "   실패 시 GripResultProjector와 동일하게 LogAction.MAP_FAILED 로깅 후 throw. upsert는 onConflictDoUpdate({target,set}).",
  "4. drizzleSchema: pgTable + primaryKey([sceneKey, attemptNum]) + 조회 패턴에 맞는 index. import 포함.",
  "5. migrationSql: 위 스키마와 1:1 일치하는 CREATE TABLE + CREATE INDEX.",
  "6. controllerWiring: schema/index.ts export * 한 줄 + ProjectionService 주입·catchUp<Name>() + controller @Post 라우트",
  "   (기존 라우트와 동일한 PinoLogger.info 로깅) + ProjectionModule providers 등록.",
  "7. TypeScript any 금지(: any, as any, any[], Record<string,any>, Promise<any>). 식별자 전체 단어",
  "   (id/url/api/db/json/http/dto/cqrs/es/llm, i/j/k 예외). catch 변수는 error 로 명명하라(주입 예시의 err 를 따르지 말 것).",
  "8. rationale: 윈도우 앵커 행을 인용해 '어디서 막혔는지'를 적고, 왜 기존 read_grip_result/read_multimodal로는 안 되는지",
  "   (필드 부재)와 왜 버전교체·보강이 아니라 신규인지 적어라.",
  "9. 코드 필드(drizzleSchema/migrationSql/projectorCode/controllerWiring) 값 안에는 마크다운 백틱 펜스(```)를 절대 넣지 말고",
  "   들여쓰기/개행 포함 순수 소스 문자열만 담아라.",
  "",
  "마지막에 아래 JSON만 코드블록으로:",
  "```json",
  '{ "proposedName": string, "purpose": string, "rationale": string,',
  '  "sourceEvents": string[], "keyColumns": string,',
  '  "fields": [{ "name": string, "dataType": string, "meaning": string }],',
  '  "drizzleSchema": string, "migrationSql": string, "projectorCode": string, "controllerWiring": string }',
  "```",
].join("\n");
